// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOhZMySgmytVfj41yAybddE0sjMGKD0s',
    appId: '1:1022717564663:web:7e70ef6decfcf903bf65f2',
    messagingSenderId: '1022717564663',
    projectId: 'inspiring-hope-321800',
    authDomain: 'inspiring-hope-321800.firebaseapp.com',
    storageBucket: 'inspiring-hope-321800.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5_uINVZkrlmNvFSIK0auBweSBdR52_A',
    appId: '1:1022717564663:android:4dfe7b00b84a7f3bbf65f2',
    messagingSenderId: '1022717564663',
    projectId: 'inspiring-hope-321800',
    storageBucket: 'inspiring-hope-321800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEGWuapc9Tzngtxal34YF_nGH_mo4HWAg',
    appId: '1:1022717564663:ios:41f5436051451f32bf65f2',
    messagingSenderId: '1022717564663',
    projectId: 'inspiring-hope-321800',
    storageBucket: 'inspiring-hope-321800.appspot.com',
    iosClientId: '1022717564663-2jgmadtelndgniqf2vd3kr5t9ahug9ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
